workflows:
  ios-webview-build:
    name: Build iOS WebView App
    environment:
      vars:
        BUNDLE_ID: "com.bckg.ios"
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the React app
        script: |
          npm run build
      - name: Sync with Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS project
        script: |
          cd ios/App
          
          # Чистим предыдущие билды (замени YourSchemeName на App)
          xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release
          
          # Архивируем проект (собираем .xcarchive)
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos archive -archivePath $HOME/build/App.xcarchive CODE_SIGN_STYLE=Automatic
          
          # Экспортируем .ipa, путь к ExportOptions.plist указать относительно папки ios/App, т.е. ../ExportOptions.plist
          xcodebuild -exportArchive -archivePath $HOME/build/App.xcarchive -exportOptionsPlist ../ExportOptions.plist -exportPath $HOME/build/ipa
    artifacts:
      - build/ipa/*.ipa
